title: driftnotes
author: Jing Lee
description:
url: "https://driftnotes.github.io"

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
